### ISSUE TITLE
pnpm serve 怎么跑都跑不起来

### ISSUE THREAD

**Issue by jg-8** [hb0730/boot-admin-ui#32]
node 16.18.1
node 18.18.2
node 19.9.0
node 14.20.1
这些版本都试过
pnpm install 后，serve 怎么都是报错
pnpm serve

> pure-admin-thin@4.4.0 serve /web/boot-admin-ui
> pnpm dev

> pure-admin-thin@4.4.0 dev /web/boot-admin-ui
> NODE_OPTIONS=--max-old-space-size=4096 vite

failed to load config from /web/boot-admin-ui/vite.config.ts
error when starting dev server:
TypeError: (0 , import_theme.default) is not a function
    at getPluginsList (/web/boot-admin-ui/vite.config.ts:515:30)
    at vite_config_default (/web/boot-admin-ui/vite.config.ts:593:14)
    at loadConfigFromFile (file:///web/boot-admin-ui/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66174:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (file:///web/boot-admin-ui/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65767:28)
    at async _createServer (file:///web/boot-admin-ui/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65044:20)
    at async CAC.<anonymous> (file:///web/boot-admin-ui/node_modules/.pnpm/vite@4.5.0_@types+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by stealth-Lee** [comment]
一样的问题，请问怎么解决的 ？
